CloneFailedException: remove "@since upcoming" from constructors javadoc, because these constructors were added in the same version as the class itself (3.0)