Add "ppc64le" to ArchUtils.
- See https://bugs.gentoo.org/972590
  Bug 972590 - dev-java/commons-lang-3.20.0:
java.lang.NullPointerException: Cannot invoke
"org.apache.commons.lang3.arch.Processor.toString()" because "<local1>"
is null
- Like #1624 but with tests